apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafanatest
spec:
  capacity:
    storage: 35Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana-pv
  local:
    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: 
          operator: In
          values:
          - node1
